### ISSUE TITLE
Update to use Postgres 16

### ISSUE THREAD

**Issue by rustprooflabs** [rustprooflabs/pgosm-flex#359]
# Details

Postgres 16 was released on 9/14.  https://www.postgresql.org/about/news/postgresql-16-released-2715/

Needs

* [x] PostGIS Docker based on Pg16  https://hub.docker.com/r/postgis/postgis/tags #360
* [x] Check for new LuaRocks #360
* [x] PgDD needs Pg16 support https://github.com/rustprooflabs/pgdd/issues/40 - 0.5.1 https://github.com/rustprooflabs/pgdd/releases/tag/0.5.1
