### ISSUE TITLE
Setup GitHub actions

### ISSUE THREAD

**Issue by rustprooflabs** [rustprooflabs/pgosm-flex#83]
I have not done anything with GH actions before.  Need to figure out how to set it up to:

* [x] Build the Docker image #104 
* [x] Push to Docker hub on success #104
* [ ] :construction: Test a known PBF file (D.C.?)  #112
* [ ] Fix #132

Resources

https://github.com/docker/build-push-action
https://github.com/VaultVulp/gp-docker-action

https://github.com/marketplace/actions/docker-run-action

**Comment by rustprooflabs** [comment]
Not really sure why this is open... closing.
